<?php
declare(strict_types=1);header('Content-Type: application/json; charset=utf-8');require __DIR__.'/auth.php';budgetRequireAuthApi();const FIRST_MONTH='2026-06';
function fail(string $m,int $s=422):never{http_response_code($s);echo json_encode(['error'=>$m]);exit;}function body():array{try{return json_decode(file_get_contents('php://input'),true,512,JSON_THROW_ON_ERROR);}catch(Throwable){fail('Données invalides.');}}
try{$c=require __DIR__.'/config.php';$pdo=new PDO("mysql:host={$c['host']};dbname={$c['database']};charset=utf8mb4",$c['username'],$c['password'],[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION]);$a=$_GET['action']??'';
if($_SERVER['REQUEST_METHOD']==='GET'&&$a==='bootstrap'){$budgets=$pdo->query("SELECT b.id,b.kind,b.name,b.period_month,b.project_date,COALESCE(SUM(p.amount),0) received FROM budgets b LEFT JOIN budget_payments p ON p.budget_id=b.id GROUP BY b.id ORDER BY COALESCE(b.period_month,b.project_date) DESC,b.created_at DESC")->fetchAll(PDO::FETCH_ASSOC);$expenses=$pdo->query("SELECT id,budget_id,type,amount,label,note,bucket,nature,status,DATE_FORMAT(entry_date,'%Y-%m-%d') date FROM entries ORDER BY entry_date DESC,created_at DESC")->fetchAll(PDO::FETCH_ASSOC);$payments=$pdo->query("SELECT id,budget_id,amount,label,DATE_FORMAT(payment_date,'%Y-%m-%d') date FROM budget_payments ORDER BY payment_date DESC,created_at DESC")->fetchAll(PDO::FETCH_ASSOC);echo json_encode(compact('budgets','expenses','payments'));exit;}
if($_SERVER['REQUEST_METHOD']!=='POST')fail('Méthode non autorisée.',405);$d=body();if($a==='budget'){$k=$d['kind']??'';$p=$d['period_month']??'';$date=$d['project_date']??'';if(!in_array($k,['grace','project'],true)||($k==='grace'&&$p<FIRST_MONTH)||($k==='project'&&$date<FIRST_MONTH))fail('Les budgets commencent en juin 2026.');$pdo->beginTransaction();$pdo->prepare('INSERT INTO budgets(id,kind,name,period_month,project_date) VALUES(?,?,?,?,?)')->execute([$d['id'],$k,trim($d['name']),$k==='grace'?$p:null,$k==='project'?$date:null]);$pdo->prepare('INSERT INTO budget_payments(id,budget_id,amount,label,payment_date) VALUES(?,?,?,?,?)')->execute([$d['payment_id'],$d['id'],$d['amount'],trim($d['payment_label']),$d['payment_date']]);$pdo->prepare("INSERT INTO entries(id,budget_id,type,amount,label,bucket,status,entry_date,source) VALUES(?,?,'expense',?,?, 'tithe','planned',?,'budget')")->execute([$d['tithe_id'],$d['id'],round((float)$d['amount']*.1),'Dîme — '.trim($d['payment_label']),$d['payment_date']]);$pdo->commit();echo json_encode(['ok'=>true]);exit;}
if($a==='expense'){if((float)($d['amount']??0)<=0||trim((string)($d['label']??''))===''||!in_array($d['status']??'',['planned','realised'],true))fail('Libellé, montant positif et statut valide requis.');if(!in_array($d['bucket']??'',['priority','dogs'],true)||($d['date']??'')<FIRST_MONTH)fail('Choisissez Priorité ou Petits chiens, à partir de juin 2026.');$note=trim((string)($d['note']??''));$nature=trim((string)($d['nature']??''));$pdo->prepare("INSERT INTO entries(id,budget_id,type,amount,label,note,bucket,nature,status,entry_date,source) VALUES(?,?,'expense',?,?,?,?,?,?,?,'budget')")->execute([$d['id'],$d['budget_id'],$d['amount'],trim($d['label']),$note!==''?$note:null,$d['bucket'],$nature!==''?$nature:null,$d['status'],$d['date']]);echo json_encode(['ok'=>true]);exit;}
if($a==='payment'){$pdo->beginTransaction();$pdo->prepare('INSERT INTO budget_payments(id,budget_id,amount,label,payment_date) VALUES(?,?,?,?,?)')->execute([$d['id'],$d['budget_id'],$d['amount'],trim($d['label']),$d['payment_date']]);$pdo->prepare("INSERT INTO entries(id,budget_id,type,amount,label,bucket,status,entry_date,source) VALUES(?,?,'expense',?,?, 'tithe','planned',?,'budget')")->execute([$d['tithe_id'],$d['budget_id'],round((float)$d['amount']*.1),'Dîme — '.trim($d['label']),$d['payment_date']]);$pdo->commit();echo json_encode(['ok'=>true]);exit;}
if($a==='budget_label'){$name=trim((string)($d['name']??''));if($name==='')fail('Le libellé est obligatoire.');$q=$pdo->prepare("UPDATE budgets SET name=? WHERE id=? AND kind='project'");$q->execute([$name,$d['id']]);if(!$q->rowCount())fail('Budget introuvable.',404);echo json_encode(['ok'=>true]);exit;}
if($a==='budget_month'){$month=(string)($d['month']??'');if($month<FIRST_MONTH||!preg_match('/^\d{4}-\d{2}$/',$month))fail('Le mois doit être à partir de juin 2026.');$q=$pdo->prepare("UPDATE budgets SET period_month=?,name=? WHERE id=? AND kind='grace'");$q->execute([$month,'Grâce '.$month,$d['id']]);if(!$q->rowCount())fail('Budget introuvable.',404);echo json_encode(['ok'=>true]);exit;}
if($a==='expense_update'){$label=trim((string)($d['label']??''));$amount=(float)($d['amount']??0);if($label===''||$amount<=0)fail('Libellé et montant (positif) requis.');$q=$pdo->prepare("UPDATE entries SET label=?,amount=? WHERE id=? AND bucket IN ('priority','dogs','tithe')");$q->execute([$label,$amount,$d['id']]);if(!$q->rowCount())fail('Dépense introuvable.',404);echo json_encode(['ok'=>true]);exit;}fail('Action inconnue.',404);
}catch(Throwable $e){if(isset($pdo)&&$pdo->inTransaction())$pdo->rollBack();fail('Impossible d’enregistrer. Vérifiez la base de données.',500);}
