const $=s=>document.querySelector(s);
const months=Array.from({length:18},(_,i)=>new Date(2026,6+i,1).toISOString().slice(0,7));
const current=new Date().toISOString().slice(0,7);
let data={tracks:[],tasks:[]},selectedMonth=months.includes(current)?current:months[0],selected=null,view=localStorage.getItem('budget-josh-objectives-view')||'cards';
const label=m=>new Intl.DateTimeFormat('fr-FR',{month:'long',year:'numeric'}).format(new Date(m+'-02'));
const shortLabel=m=>new Intl.DateTimeFormat('fr-FR',{month:'short',year:'numeric'}).format(new Date(m+'-02'));
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function api(action,body){const r=await fetch('goals-grid-api.php'+(action?'?action='+encodeURIComponent(action):''),{method:body?'POST':'GET',headers:body?{'Content-Type':'application/json'}:{},body:body?JSON.stringify(body):undefined});const j=await r.json();if(!r.ok)throw Error(j.error||'Erreur');return j}
const tasksFor=(id,month)=>data.tasks.filter(t=>t.track_id===id&&t.goal_month===month);
const duplicateTitle=g=>data.tracks.filter(x=>x.title.trim().toLowerCase()===g.title.trim().toLowerCase()).length>1;
const progress=g=>{const rows=data.tasks.filter(t=>t.track_id===g.id),done=rows.filter(t=>t.status==='realised').length;return {done,total:rows.length,ratio:rows.length?done/rows.length*100:0}};
function renderMetrics(){const all=data.tasks,done=all.filter(t=>t.status==='realised'),thisMonth=all.filter(t=>t.goal_month===selectedMonth),last=months.filter(m=>m<=current).slice(-3),recent=all.filter(t=>last.includes(t.goal_month));$('#metrics').innerHTML='<article class="metric"><small>'+esc(label(selectedMonth))+'</small><b>'+thisMonth.filter(t=>t.status==='realised').length+' / '+thisMonth.length+'</b><small>actions réalisées</small></article><article class="metric"><small>3 derniers mois</small><b>'+recent.filter(t=>t.status==='realised').length+' / '+recent.length+'</b><small>réalisées / prévues</small></article><article class="metric"><small>Depuis juillet 2026</small><b>'+done.length+' / '+all.length+'</b><small>réalisées / prévues</small></article>'}
function taskHtml(t){return '<div class="task '+(t.status==='realised'?'done':'')+'"><button data-toggle="'+esc(t.id)+'" aria-label="Changer le statut">'+(t.status==='realised'?'✓':'○')+'</button><span>'+esc(t.title)+'</span></div>'}
function goalActions(g){return '<div class="goal-actions"><button data-edit-track="'+esc(g.id)+'" title="Modifier">✎</button><button class="delete-goal" data-delete-track="'+esc(g.id)+'" title="Supprimer">×</button></div>'}
function renderCards(){const html=data.tracks.map(g=>{const rows=tasksFor(g.id,selectedMonth),p=progress(g),warning=duplicateTitle(g)?'<small style="display:block;color:#b53e25;margin-top:7px">Doublon possible : vérifie cet objectif.</small>':'';return '<article class="goal-card"><div class="goal-head"><div><h2>'+esc(g.title)+'</h2>'+warning+'</div>'+goalActions(g)+'</div><div class="goal-progress"><i style="width:'+p.ratio+'%"></i></div><div class="goal-meta"><span>'+p.done+' réalisée'+(p.done>1?'s':'')+' / '+p.total+'</span><span>'+Math.round(p.ratio)+' %</span></div><div class="month-label '+(selectedMonth===current?'current':'')+'"><span>'+esc(label(selectedMonth))+'</span><small>'+rows.length+' action'+(rows.length>1?'s':'')+'</small></div><div class="task-list">'+(rows.length?rows.map(taskHtml).join(''):'<p class="empty">Aucune action pour ce mois.</p>')+'</div><button class="add-task" data-add="'+esc(g.id)+'" data-month="'+esc(selectedMonth)+'">+ Ajouter une action</button></article>'}).join('');$('#cards').innerHTML=html||'<p class="empty">Ajoutez un objectif global pour commencer.</p>'}
function renderGrid(){const head='<tr><th class="track">Objectif global</th>'+months.map(m=>'<th class="'+(m===current?'current':'')+'">'+esc(shortLabel(m))+'</th>').join('')+'</tr>';const rows=data.tracks.map(g=>'<tr><td class="track"><span>'+esc(g.title)+'</span>'+goalActions(g)+'</td>'+months.map(m=>'<td class="'+(m===current?'current':'')+'">'+tasksFor(g.id,m).map(taskHtml).join('')+'<button class="add-task" data-add="'+esc(g.id)+'" data-month="'+m+'">+ Ajouter</button></td>').join('')+'</tr>').join('');$('#months').innerHTML=head;$('#rows').innerHTML=rows||'<tr><td colspan="19" class="empty">Ajoutez un objectif global pour commencer.</td></tr>'}
function setView(next){view=next;localStorage.setItem('budget-josh-objectives-view',view);$('#cardsView').classList.toggle('hidden',view==='grid');$('#gridView').classList.toggle('visible',view==='grid');$('#viewToggle').textContent=view==='grid'?'Vue cartes':'Vue grille'}
function openTask(trackId,month){selected={track_id:trackId,month};$('#taskTitle').textContent='Action pour '+label(month);$('#taskDialog').showModal()}
function wire(){document.querySelectorAll('[data-add]').forEach(x=>x.onclick=()=>openTask(x.dataset.add,x.dataset.month));document.querySelectorAll('[data-toggle]').forEach(x=>x.onclick=async()=>{try{await api('toggle',{id:x.dataset.toggle});await load()}catch(e){alert(e.message)}});document.querySelectorAll('[data-edit-track]').forEach(x=>x.onclick=async()=>{const g=data.tracks.find(t=>t.id===x.dataset.editTrack),title=prompt('Nom de l’objectif :',g?.title||'');if(title===null||!title.trim())return;try{await api('track_update',{id:x.dataset.editTrack,title:title.trim()});await load()}catch(e){alert(e.message)}});document.querySelectorAll('[data-delete-track]').forEach(x=>x.onclick=async()=>{const g=data.tracks.find(t=>t.id===x.dataset.deleteTrack);if(!g||!confirm('Supprimer « '+g.title+' » et toutes ses actions ?'))return;try{await api('track_delete',{id:g.id});await load()}catch(e){alert(e.message)}})}
function render(){renderMetrics();renderCards();renderGrid();setView(view);wire()}
async function load(){try{data=await api('');render()}catch(e){alert(e.message)}}
months.forEach(m=>{const option=document.createElement('option');option.value=m;option.textContent=label(m);if(m===selectedMonth)option.selected=true;$('#monthFilter').append(option)});
$('#monthFilter').onchange=e=>{selectedMonth=e.target.value;render()};$('#viewToggle').onclick=()=>setView(view==='cards'?'grid':'cards');$('#addTrack').onclick=()=>$('#trackDialog').showModal();document.querySelectorAll('.close').forEach(x=>x.onclick=()=>x.closest('dialog').close());
$('#trackForm').onsubmit=async e=>{e.preventDefault();try{await api('track',{id:crypto.randomUUID(),title:$('#trackTitle').value.trim()});$('#trackDialog').close();e.target.reset();await load()}catch(err){alert(err.message)}};
$('#taskForm').onsubmit=async e=>{e.preventDefault();try{await api('task',{id:crypto.randomUUID(),track_id:selected.track_id,goal_month:selected.month,title:$('#taskText').value.trim()});$('#taskDialog').close();e.target.reset();await load()}catch(err){alert(err.message)}};
load();
