(()=>{
  const $=s=>document.querySelector(s),fmt=n=>new Intl.NumberFormat('fr-FR',{maximumFractionDigits:0}).format(Number(n)||0)+' F CFA',pct=n=>`${Math.round(Number(n)||0)} %`;
  const state={db:{budgets:[],expenses:[]},limits:{},selected:'all'};
  const api=async(action,data,endpoint='api.php')=>{const r=await fetch(`${endpoint}?action=${encodeURIComponent(action)}`,{method:data?'POST':'GET',headers:data?{'Content-Type':'application/json'}:{},body:data?JSON.stringify(data):undefined});const j=await r.json();if(!r.ok)throw Error(j.error||'Erreur');return j};
  const active=e=>e.type==='expense'&&e.status!=='cancelled';
  const scopedBudgets=()=>state.selected==='all'?state.db.budgets:state.db.budgets.filter(b=>b.id===state.selected);
  const scopedEntries=()=>state.db.expenses.filter(e=>active(e)&&(state.selected==='all'||e.budget_id===state.selected));
  const sum=xs=>xs.reduce((n,e)=>n+Number(e.amount||0),0);
  const budgetName=b=>b.kind==='grace'?`Grâce — ${new Intl.DateTimeFormat('fr-FR',{month:'long',year:'numeric'}).format(new Date(`${b.period_month}-02`))}`:b.name;
  const received=()=>scopedBudgets().reduce((n,b)=>n+Number(b.received||0),0);
  const expenses=()=>scopedEntries(),realised=()=>sum(expenses().filter(e=>e.status==='realised')),planned=()=>sum(expenses().filter(e=>e.status==='planned'));
  const cat=key=>expenses().filter(e=>key==='priority'?(e.bucket==='priority'||e.bucket==='tithe'):e.bucket===key);
  const categoryStats=key=>{const rows=cat(key);return {realised:sum(rows.filter(e=>e.status==='realised')),planned:sum(rows.filter(e=>e.status==='planned'))}};
  const limitFor=key=>{const l=state.limits[key];if(!l||Number(l.value)<=0)return null;const ceiling=l.mode==='percent'?received()*Number(l.value)/100:Number(l.value);return {...l,ceiling}};
  function render(){const income=received(),real=realised(),plan=planned(),engaged=real+plan;$('#scopeLabel').textContent=state.selected==='all'?'Tous les budgets':budgetName(state.db.budgets.find(b=>b.id===state.selected)||{});$('#metrics').innerHTML=[['Reçu',income],['Réalisé',real],['Prévu',plan],['Disponible réel',income-real],['Disponible engagé',income-engaged]].map(([label,value])=>`<article class="metric"><b>${fmt(value)}</b><small>${label}</small></article>`).join('');renderAlerts();renderCategories();renderNatures();renderHints()}
  function renderAlerts(){const rows=['priority','dogs'].map(key=>{const s=categoryStats(key),engaged=s.realised+s.planned,l=limitFor(key);return {key,engaged,l}}).filter(x=>x.l);if(!rows.length){$('#alerts').innerHTML='<p class="empty">Aucun plafond configuré. Choisis un montant ou un pourcentage ci-dessous pour activer les alertes.</p>';return}$('#alerts').innerHTML=rows.map(({key,engaged,l})=>{const ratio=l.ceiling?engaged/l.ceiling:0,level=ratio>=1?'danger':ratio>=.8?'warning':'ok',title=key==='priority'?'Priorités':'Petits chiens',message=level==='danger'?`Plafond dépassé de ${fmt(engaged-l.ceiling)}.`:level==='warning'?`Il reste ${fmt(l.ceiling-engaged)} avant le plafond.`:'La consommation reste sous contrôle.';return `<article class="alert ${level}"><i class="alert-dot"></i><div><b>${title} — ${pct(ratio*100)} du plafond</b><small>${message} Engagement : ${fmt(engaged)} sur ${l.mode==='percent'?`${l.value} % des revenus (${fmt(l.ceiling)})`:fmt(l.ceiling)}.</small></div></article>`}).join('')}
  function renderCategories(){const all=expenses(),max=Math.max(...['priority','dogs'].map(k=>{const s=categoryStats(k);return s.realised+s.planned}),1);$('#categories').innerHTML=['priority','dogs'].map(key=>{const s=categoryStats(key),engaged=s.realised+s.planned,title=key==='priority'?'Priorités':'Petits chiens';return `<article class="category ${key==='dogs'?'dogs':''}"><div class="category-head"><h3>${title}</h3><strong>${fmt(engaged)}</strong></div><small>${all.length?Math.round(engaged/(sum(all)||1)*100):0} % de toutes les dépenses engagées</small><div class="bar"><i style="width:${Math.min(100,engaged/max*100)}%"></i></div><div class="category-meta"><span>Réalisé ${fmt(s.realised)}</span><span>Prévu ${fmt(s.planned)}</span></div></article>`}).join('')}
  function renderNatures(){const rows={};expenses().forEach(e=>{const name=(e.nature||'Sans nature').trim()||'Sans nature';rows[name]=(rows[name]||0)+Number(e.amount||0)});const top=Object.entries(rows).sort((a,b)=>b[1]-a[1]).slice(0,3),max=top[0]?.[1]||1;$('#natures').innerHTML=top.length?top.map(([name,value])=>`<article class="nature"><div class="nature-head"><b>${escapeHtml(name)}</b><strong>${fmt(value)}</strong></div><small>${pct(value/(sum(expenses())||1)*100)} des dépenses engagées</small><div class="bar"><i style="width:${value/max*100}%"></i></div></article>`).join(''):'<p class="empty">Aucune dépense à analyser.</p>'}
  function renderHints(){['priority','dogs'].forEach(key=>{const l=state.limits[key],hint=$(`#${key}Hint`),input=$(`#${key}Value`),mode=$(`#${key}Mode`);if(!l||Number(l.value)<=0){hint.textContent='Laisser à 0 pour désactiver.';input.value='';return}mode.value=l.mode;hint.textContent=l.mode==='percent'?`Plafond actuel : ${fmt(received()*Number(l.value)/100)} pour ce périmètre.`:`Plafond actuel : ${fmt(l.value)}.`;input.value=Number(l.value)})}
  function escapeHtml(value){return String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
  function fillBudgetFilter(){const select=$('#budgetFilter');select.innerHTML='<option value="all">Tous les budgets</option>'+state.db.budgets.slice().sort((a,b)=>(a.period_month||a.project_date).localeCompare(b.period_month||b.project_date)).map(b=>`<option value="${b.id}">${escapeHtml(budgetName(b))}</option>`).join('');select.value=state.selected}
  async function load(){try{const [db,limits]=await Promise.all([api('bootstrap'),api('limits',undefined,'limits-api.php')]);state.db=db;state.limits=limits.limits||{};fillBudgetFilter();render()}catch(e){$('#alerts').innerHTML=`<p class="empty">${escapeHtml(e.message)}</p>`}}
  $('#budgetFilter').onchange=e=>{state.selected=e.target.value;render()};$('#refresh').onclick=load;
  $('#limitsForm').onsubmit=async e=>{e.preventDefault();const payload={priority:{mode:$('#priorityMode').value,value:Number($('#priorityValue').value)||0},dogs:{mode:$('#dogsMode').value,value:Number($('#dogsValue').value)||0}};try{await api('limits',payload,'limits-api.php');state.limits={priority:payload.priority,dogs:payload.dogs};$('#settingsStatus').textContent='Plafonds enregistrés.';render()}catch(err){$('#settingsStatus').textContent=err.message}};
  ['priority','dogs'].forEach(key=>{$(`#${key}Mode`).onchange=renderHints});load();
})();
